version: "2"
services:
    api:
        build: .
        container_name: api
        command: /sbin/my_init
        env_file: ./build/app.env
        environment:
            - TERM=xterm
        depends_on:
            - db
        ports:
            - 80:80
        volumes:
            - ./:/code/api
    db:
        image: mysql:5.7
        container_name: db
        env_file: ./build/mysql.env
        environment:
            - TERM=xterm
        ports:
            - 3306:3306
        volumes:
            # - ./build/performance.cnf:/etc/mysql/conf.d/performance.cnf
            - ./data:/var/lib/mysql
        user: mysql
